### ISSUE TITLE
Dupplicated citizenship attributes

### ISSUE THREAD

**Issue by sohgo** [tanupoo/proto-patient-entry#1]
https://github.com/tanupoo/penguin/blob/ac554bea6e388dad76f795df23ea649a8b8a0f5c/modelStep2.py#L79
https://github.com/tanupoo/penguin/blob/ac554bea6e388dad76f795df23ea649a8b8a0f5c/modelStep2.py#L81
citizenship が２つ定義されていました。

**Comment by tanupoo** [comment]
ありがとうございます！
